// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puqkharjrkcqhnffgjeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1cWtoYXJqcmtjcWhuZmZnamViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMDc5ODcsImV4cCI6MjA1MTU4Mzk4N30.G0vnXrI9E5hsxIB5rfOxFapebjY8VP6S9jMqhhv7S-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);